<?php
/*
* Template Name: Privacy Policy
*/
get_header(); ?>
	<?php
		// include('app/render/single.php');
	?>


<section class="section-padding bg-light">


	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8">

				<h1 class="text-primary"> Privacy Policy</h1>
				<p>
					This Privacy Policy was last modified on November 27, 2015
				</p>
				<p>

					GreenTec Capital Partners ("us", "we", or "our") operates http://www.grentec-capital.com (the"Site").
				</p>
				<p>
					This page informs you of our policies regarding the collection, use and disclosure of Personal Information we receive from users of the Site.We use your Personal Information only for providing and improving the Site. By using the Site, you agree to the collection and use of information in accordance with this policy.
				</p>
			</div>
			<div class="col-12 col-md-4">

			</div>
		</div>
	</div>


	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8">

				<h3>Information Collection and Use</h3>
				<p>
					While using our Site, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to your name ("Personal  Information").
				</p>
			</div>
			<div class="col-12 col-md-4">

			</div>
		</div>
	</div>


	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8">

				<h3>Log Data</h3>
				<p>
					Like many site operators, we collect information that your browser sends whenever you visit our Site ("Log Data"). This Log Data may include information such as your computer's Internet Protocol ("IP") address, browser type, browser version, the pages of our Site that you visit, the time and date of your visit, the time spent on those pages and other statistics.
				</p>
			</div>
			<div class="col-12 col-md-4">

			</div>
		</div>
	</div>


	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8">

				<h3>Cookies</h3>
				<p>
					Cookies are files with small amount of data, which may include an anonymous unique identifier. Cookies are sent to your browser from a web site and stored on your computer's hard drive. Like many sites, we use "cookies" to collect information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies,you may not be able to use some portions of our  Site.
				</p>
			</div>
			<div class="col-12 col-md-4">

			</div>
		</div>
	</div>


	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8">

				<h3>Security</h3>
				<p>
					The security of your Personal Information is important to us, but remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security.
				</p>
			</div>
			<div class="col-12 col-md-4">

			</div>
		</div>
	</div>


	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8">

				<h3>Google Analytics</h3>
				<p>
					This website uses Google Analytics to help analyze how users use the site, to do reports on website activities, and to offer other services related to using this website and the internet. The tool uses "cookies," which are text files placed on your computer, to collect standard Internet log information and visitor behavior information in an anonymous form. The information generated by the cookie about your use of the website (including IP address) is transmitted to Google. This information is then used to evaluate visitors' us of the website and to compile statistical reports on website activity for GreenTec Capital Partners.
				</p>
				<p>
					We will never (and will not allow any third party to) use the statistical analytics tool to track or to collect any Personally Identifiable Information (PII) of visitors to our site. Google will not associate your IP address with any other data held by Google. Neither we nor Google will link, or seek to link, an IP address with the identity of a computer user. We will not associate any data gathered from this site with any Personally Identifiable Information from any source, unless you explicitly submit that information via a fill-in form on our website.
				</p>
				<p>
					As stated above, you can instruct your browser to refuse all cookies. In case you activate IP anonymization, your IP address within the European Union member is shortened before the transmission to the Google server. Only as an exception the full IP address is transmitted to the Google server in the US and shortened there. Additionally, you can avoid the collection of data generated by the cookie and related to your use of this website, including your IP address, by google and the processing of this data by google. For this, please download and install the browser-plugin under the following link: <br />
					<a href="http://tools.google.com/dlpage/gaoptout?hl=de">http://tools.google.com/dlpage/gaoptout?hl=de</a>
				</p>
				<p>
					All of our activity falls within the bounds of the <a href="http://www.google.com/analytics/tos.html">Google Analytics Terms of Service</a>.
				</p>
			</div>
			<div class="col-12 col-md-4">

			</div>
		</div>
	</div>


	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8">

				<h3>Changes to this Privacy  Policy</h3>
				<p>
					GreenTec Capital Partners may update this Privacy Policy from time to time. We  will notify you of any changes by posting the new Privacy Policy on the Site. You are advised to review this Privacy Policy periodically for any changes.
				</p>
			</div>
			<div class="col-12 col-md-4">

			</div>
		</div>
	</div>


	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8">

				<h3>Contact us</h3>
				<p>
					If you have any questions about this Privacy Policy, please contact us at
					<a href="mailto:info@greentec-capital.com?subject=Website%20Inquiry">info@greentec-capital.com</a>

				</p>
			</div>
			<div class="col-12 col-md-4">

			</div>
		</div>
	</div>







</section>


<?php get_footer(); ?>
